export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "3e14d8b0": [() => import(/* webpackChunkName: "3e14d8b0" */ "@site/docs/recursion-backtracking/towers-of-hanoi.md"), "@site/docs/recursion-backtracking/towers-of-hanoi.md", require.resolveWeak("@site/docs/recursion-backtracking/towers-of-hanoi.md")],
  "4c678320": [() => import(/* webpackChunkName: "4c678320" */ "@site/src/pages/markdown-page.mdx"), "@site/src/pages/markdown-page.mdx", require.resolveWeak("@site/src/pages/markdown-page.mdx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "641b0069": [() => import(/* webpackChunkName: "641b0069" */ "@generated/docusaurus-plugin-content-docs/default/p/dsa-046.json"), "@generated/docusaurus-plugin-content-docs/default/p/dsa-046.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/dsa-046.json")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "bce4e7d6": [() => import(/* webpackChunkName: "bce4e7d6" */ "@site/docs/recursion-backtracking/index.md"), "@site/docs/recursion-backtracking/index.md", require.resolveWeak("@site/docs/recursion-backtracking/index.md")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "e6020544": [() => import(/* webpackChunkName: "e6020544" */ "@site/docs/recursion-backtracking/check-if-array-is-sorted-using-recursion.md"), "@site/docs/recursion-backtracking/check-if-array-is-sorted-using-recursion.md", require.resolveWeak("@site/docs/recursion-backtracking/check-if-array-is-sorted-using-recursion.md")],};
